/**
 * Created by gsolovyev on 7/4/17.
 */
ORDER_DIRECTION_BUY="buy";
ORDER_DIRECTION_SELL="sell";
ADVICE_KEEP = "keep";
ADVICE_REPLACE = "replace";
ERROR_CODE_BAD_ORDER = "badorder"
ERROR_CODE_NO_DATA = "nodata";
ERROR_CODE_ACCOUNT_EMPTY = "empty";
ERROR_CODE_NOT_FOUND = "notfound";
ERROR_CODE_UNKOWN = "unknown";
ERROR_CODE_NOT_ENOUGH_BALANCE = "notenoughbalance";
module.exports = {
    BUY:ORDER_DIRECTION_BUY,
    SELL:ORDER_DIRECTION_SELL,
    KEEP:ADVICE_KEEP,
    REPLACE:ADVICE_REPLACE,
    BAD_ORDER:ERROR_CODE_BAD_ORDER,
    NO_DATA:ERROR_CODE_NO_DATA,
    ACCOUNT_EMPTY:ERROR_CODE_ACCOUNT_EMPTY,
    NOT_FOUND:ERROR_CODE_NOT_FOUND,
    UNKNOWN:ERROR_CODE_NOT_FOUND,
    NOT_ENOUGH_BALANCE:ERROR_CODE_NOT_ENOUGH_BALANCE
}